# Generated by Django 5.0.6 on 2024-05-31 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriaapp', '0001_initial'),
        ('orm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoriaapp.categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
