# Generated by Django 5.0.6 on 2024-05-31 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_alter_producto_categoria_delete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
