# Generated by Django 5.0.6 on 2024-05-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0003_remove_producto_categoria'),
        ('productoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='productos',
            field=models.ManyToManyField(to='productoapp.producto'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
